// =============================================================================
// Worker Scaffold Generator — WASM → deployable Cloudflare Worker bundle
// =============================================================================
// Generates a complete Cloudflare Worker bundle from compiled WASM binary:
//   worker.js  — ES Module Worker entry point with self-contained host imports
//   program.wasm — compiled WASM binary
//   wrangler.toml — Wrangler v3 configuration
//
// Host functions are derived from ALL_BUILTINS at generation time — the Worker
// script is self-contained (no external imports) and mirrors the behavior of
// CloudflareHostAdapter.

import { ALL_BUILTINS } from "../builtins/builtin-meta.js";

// =============================================================================
// Types
// =============================================================================

/** Configuration for the generated Worker. */
export interface WorkerConfig {
    /** Worker name — used in wrangler.toml and the deployment URL. */
    name: string;
    /** Wrangler compatibility date (default: "2024-01-01"). */
    compatibilityDate?: string;
    /** Optional KV namespace bindings. */
    kvNamespaces?: { binding: string; id: string }[];
}

/** A single file in the generated Worker bundle. */
export interface WorkerBundleFile {
    /** Relative path within the bundle (e.g., "worker.js"). */
    path: string;
    /** File content — string for text files, Uint8Array for binary. */
    content: string | Uint8Array;
}

/** A deployable Worker bundle — a set of files ready for `wrangler deploy`. */
export interface WorkerBundle {
    files: WorkerBundleFile[];
}

/** Result of scaffold generation. */
export type ScaffoldResult =
    | { ok: true; bundle: WorkerBundle }
    | { ok: false; error: string };

// =============================================================================
// Host function names — derived from the builtin registry
// =============================================================================

/** All host-kind builtin names, derived from ALL_BUILTINS at module load time. */
const HOST_BUILTIN_NAMES: readonly string[] = ALL_BUILTINS
    .filter(b => b.impl.kind === "host")
    .map(b => b.name);

// =============================================================================
// Worker.js template generation
// =============================================================================

/**
 * Generate the self-contained Worker entry point JavaScript.
 *
 * The generated script:
 * - Imports WASM from './program.wasm'
 * - Defines string read/write helpers (same as browser worker pattern)
 * - Defines all host import functions inline
 * - Exports a Module Worker fetch handler
 */
function generateWorkerJs(): string {
    return `// Auto-generated Edict Worker — do not edit
// Generated by edict-lang scaffold generator
import wasmModule from './program.wasm';

const encoder = new TextEncoder();
const decoder = new TextDecoder();

// ── String helpers (WASM memory format: 4-byte LE length prefix + UTF-8 data) ──

function readString(memory, ptr) {
    const buf = memory.buffer;
    const view = new DataView(buf);
    const len = view.getInt32(ptr, true);
    const bytes = new Uint8Array(buf, ptr + 4, len);
    return decoder.decode(bytes);
}

function allocateHeap(exports, size) {
    const ptr = exports.__get_heap_ptr();
    const aligned = Math.ceil(size / 8) * 8;
    exports.__set_heap_ptr(ptr + aligned);
    return ptr;
}

function writeString(exports, str) {
    const encoded = encoder.encode(str);
    const totalSize = 4 + encoded.length;
    const ptr = allocateHeap(exports, totalSize);
    const buf = exports.memory.buffer;
    const view = new DataView(buf);
    view.setInt32(ptr, encoded.length, true);
    new Uint8Array(buf, ptr + 4, encoded.length).set(encoded);
    return ptr;
}

export default {
    async fetch(request, env) {
        const outputParts = [];
        let wasmExports = null;

        // ── Host import functions ──────────────────────────────────────

        const hostFunctions = {
            // Core
            print: (ptr) => {
                outputParts.push(readString(wasmExports.memory, ptr));
                return ptr;
            },
            println: (ptr) => {
                outputParts.push(readString(wasmExports.memory, ptr) + "\\n");
                return ptr;
            },
            string_replace: (hayPtr, needlePtr, replPtr) => {
                const h = readString(wasmExports.memory, hayPtr);
                const n = readString(wasmExports.memory, needlePtr);
                const r = readString(wasmExports.memory, replPtr);
                return writeString(wasmExports, h.replaceAll(n, r));
            },

            // String
            string_length: (ptr) => readString(wasmExports.memory, ptr).length,
            substring: (ptr, start, end) => writeString(wasmExports, readString(wasmExports.memory, ptr).substring(start, end)),
            string_concat: (a, b) => writeString(wasmExports, readString(wasmExports.memory, a) + readString(wasmExports.memory, b)),
            string_indexOf: (hay, needle) => readString(wasmExports.memory, hay).indexOf(readString(wasmExports.memory, needle)),
            toUpperCase: (ptr) => writeString(wasmExports, readString(wasmExports.memory, ptr).toUpperCase()),
            toLowerCase: (ptr) => writeString(wasmExports, readString(wasmExports.memory, ptr).toLowerCase()),
            string_trim: (ptr) => writeString(wasmExports, readString(wasmExports.memory, ptr).trim()),
            string_startsWith: (s, p) => readString(wasmExports.memory, s).startsWith(readString(wasmExports.memory, p)) ? 1 : 0,
            string_endsWith: (s, p) => readString(wasmExports.memory, s).endsWith(readString(wasmExports.memory, p)) ? 1 : 0,
            string_contains: (hay, needle) => readString(wasmExports.memory, hay).includes(readString(wasmExports.memory, needle)) ? 1 : 0,
            string_repeat: (ptr, n) => writeString(wasmExports, readString(wasmExports.memory, ptr).repeat(n)),
            string_eq: (a, b) => readString(wasmExports.memory, a) === readString(wasmExports.memory, b) ? 1 : 0,

            // Type conversion
            intToString: (n) => writeString(wasmExports, String(n)),
            floatToString: (n) => writeString(wasmExports, String(n)),
            boolToString: (n) => writeString(wasmExports, n ? "true" : "false"),
            toString: (ptr) => ptr,
            floatToInt: (n) => Math.trunc(n) | 0,
            intToFloat: (n) => n,
            int64ToFloat: (n) => Number(n),
            int64ToInt: (n) => Number(n) | 0,
            int64ToString: (n) => writeString(wasmExports, String(n)),
            intToInt64: (n) => BigInt(n),

            // Math
            abs: (x) => Math.abs(x),
            min: (a, b) => Math.min(a, b),
            max: (a, b) => Math.max(a, b),
            pow: (base, exp) => Math.pow(base, exp) | 0,
            sqrt: (x) => Math.sqrt(x),
            floor: (x) => Math.floor(x) | 0,
            ceil: (x) => Math.ceil(x) | 0,
            round: (x) => Math.round(x) | 0,

            // Option (heap-allocated tagged unions)
            isSome: (ptr) => new DataView(wasmExports.memory.buffer).getInt32(ptr, true) === 1 ? 1 : 0,
            isNone: (ptr) => new DataView(wasmExports.memory.buffer).getInt32(ptr, true) === 0 ? 1 : 0,
            unwrap: (ptr) => {
                const view = new DataView(wasmExports.memory.buffer);
                if (view.getInt32(ptr, true) === 1) return view.getInt32(ptr + 8, true);
                throw new Error("unwrap called on None");
            },
            unwrapOr: (ptr, def) => {
                const view = new DataView(wasmExports.memory.buffer);
                return view.getInt32(ptr, true) === 1 ? view.getInt32(ptr + 8, true) : def;
            },

            // Result (heap-allocated tagged unions)
            isOk: (ptr) => new DataView(wasmExports.memory.buffer).getInt32(ptr, true) === 0 ? 1 : 0,
            isErr: (ptr) => new DataView(wasmExports.memory.buffer).getInt32(ptr, true) === 1 ? 1 : 0,
            unwrapOk: (ptr) => {
                const view = new DataView(wasmExports.memory.buffer);
                if (view.getInt32(ptr, true) === 0) return view.getInt32(ptr + 8, true);
                throw new Error("unwrapOk called on Err");
            },
            unwrapErrOr: (ptr, def) => {
                const view = new DataView(wasmExports.memory.buffer);
                return view.getInt32(ptr, true) === 1 ? view.getInt32(ptr + 8, true) : def;
            },
            unwrapOkOr: (ptr, def) => {
                const view = new DataView(wasmExports.memory.buffer);
                return view.getInt32(ptr, true) === 0 ? view.getInt32(ptr + 8, true) : def;
            },
            unwrapErr: (ptr) => {
                const view = new DataView(wasmExports.memory.buffer);
                if (view.getInt32(ptr, true) === 1) return view.getInt32(ptr + 8, true);
                throw new Error("unwrapErr called on Ok");
            },

            // Array (host-kind builtins; HOFs like array_map are WASM-native)
            array_length: (ptr) => new DataView(wasmExports.memory.buffer).getInt32(ptr, true),
            array_get: (ptr, idx) => {
                const view = new DataView(wasmExports.memory.buffer);
                const len = view.getInt32(ptr, true);
                if (idx < 0 || idx >= len) throw new Error("array_get: index out of bounds");
                return view.getInt32(ptr + 4 + idx * 4, true);
            },
            array_set: (ptr, idx, val) => {
                const view = new DataView(wasmExports.memory.buffer);
                const len = view.getInt32(ptr, true);
                if (idx < 0 || idx >= len) throw new Error("array_set: index out of bounds");
                // Clone array with updated element
                const newPtr = allocateHeap(wasmExports, 4 + len * 4);
                const buf = wasmExports.memory.buffer;
                new Uint8Array(buf, newPtr, 4 + len * 4).set(new Uint8Array(buf, ptr, 4 + len * 4));
                new DataView(buf).setInt32(newPtr + 4 + idx * 4, val, true);
                return newPtr;
            },
            array_push: (ptr, val) => {
                const view = new DataView(wasmExports.memory.buffer);
                const len = view.getInt32(ptr, true);
                const newLen = len + 1;
                const newPtr = allocateHeap(wasmExports, 4 + newLen * 4);
                const buf = wasmExports.memory.buffer;
                new Uint8Array(buf, newPtr, 4 + len * 4).set(new Uint8Array(buf, ptr, 4 + len * 4));
                const nv = new DataView(buf);
                nv.setInt32(newPtr, newLen, true);
                nv.setInt32(newPtr + 4 + len * 4, val, true);
                return newPtr;
            },
            array_pop: (ptr) => {
                const view = new DataView(wasmExports.memory.buffer);
                const len = view.getInt32(ptr, true);
                if (len === 0) return ptr;
                const newLen = len - 1;
                const newPtr = allocateHeap(wasmExports, 4 + newLen * 4);
                const buf = wasmExports.memory.buffer;
                const nv = new DataView(buf);
                nv.setInt32(newPtr, newLen, true);
                new Uint8Array(buf, newPtr + 4, newLen * 4).set(new Uint8Array(buf, ptr + 4, newLen * 4));
                return newPtr;
            },
            array_concat: (aPtr, bPtr) => {
                const buf = wasmExports.memory.buffer;
                const view = new DataView(buf);
                const aLen = view.getInt32(aPtr, true);
                const bLen = view.getInt32(bPtr, true);
                const newLen = aLen + bLen;
                const newPtr = allocateHeap(wasmExports, 4 + newLen * 4);
                const nv = new DataView(wasmExports.memory.buffer);
                nv.setInt32(newPtr, newLen, true);
                new Uint8Array(wasmExports.memory.buffer, newPtr + 4, aLen * 4).set(new Uint8Array(buf, aPtr + 4, aLen * 4));
                new Uint8Array(wasmExports.memory.buffer, newPtr + 4 + aLen * 4, bLen * 4).set(new Uint8Array(buf, bPtr + 4, bLen * 4));
                return newPtr;
            },
            array_slice: (ptr, start, end) => {
                const view = new DataView(wasmExports.memory.buffer);
                const len = view.getInt32(ptr, true);
                const s = Math.max(0, start);
                const e = Math.min(len, end);
                const sliceLen = Math.max(0, e - s);
                const newPtr = allocateHeap(wasmExports, 4 + sliceLen * 4);
                const nv = new DataView(wasmExports.memory.buffer);
                nv.setInt32(newPtr, sliceLen, true);
                if (sliceLen > 0) {
                    new Uint8Array(wasmExports.memory.buffer, newPtr + 4, sliceLen * 4)
                        .set(new Uint8Array(wasmExports.memory.buffer, ptr + 4 + s * 4, sliceLen * 4));
                }
                return newPtr;
            },
            array_reverse: (ptr) => {
                const view = new DataView(wasmExports.memory.buffer);
                const len = view.getInt32(ptr, true);
                const newPtr = allocateHeap(wasmExports, 4 + len * 4);
                const nv = new DataView(wasmExports.memory.buffer);
                nv.setInt32(newPtr, len, true);
                for (let i = 0; i < len; i++) {
                    nv.setInt32(newPtr + 4 + i * 4, view.getInt32(ptr + 4 + (len - 1 - i) * 4, true), true);
                }
                return newPtr;
            },
            array_contains: (ptr, val) => {
                const view = new DataView(wasmExports.memory.buffer);
                const len = view.getInt32(ptr, true);
                for (let i = 0; i < len; i++) {
                    if (view.getInt32(ptr + 4 + i * 4, true) === val) return 1;
                }
                return 0;
            },
            array_isEmpty: (ptr) => new DataView(wasmExports.memory.buffer).getInt32(ptr, true) === 0 ? 1 : 0,
            array_sort: (ptr) => {
                const view = new DataView(wasmExports.memory.buffer);
                const len = view.getInt32(ptr, true);
                const vals = [];
                for (let i = 0; i < len; i++) vals.push(view.getInt32(ptr + 4 + i * 4, true));
                vals.sort((a, b) => a - b);
                const newPtr = allocateHeap(wasmExports, 4 + len * 4);
                const nv = new DataView(wasmExports.memory.buffer);
                nv.setInt32(newPtr, len, true);
                for (let i = 0; i < len; i++) nv.setInt32(newPtr + 4 + i * 4, vals[i], true);
                return newPtr;
            },

            // JSON
            jsonParse: (ptr) => {
                try {
                    const str = readString(wasmExports.memory, ptr);
                    JSON.parse(str); // validate
                    return ptr; // return original string pointer
                } catch { return 0; }
            },
            jsonStringify: (ptr) => {
                const str = readString(wasmExports.memory, ptr);
                return writeString(wasmExports, JSON.stringify(str));
            },

            // Random
            randomInt: (min, max) => Math.floor(Math.random() * (max - min + 1)) + min,
            randomFloat: () => Math.random(),
            randomUuid: () => writeString(wasmExports, crypto.randomUUID()),

            // DateTime
            now: () => Date.now(),
            formatDate: (ms) => writeString(wasmExports, new Date(ms).toISOString()),
            parseDate: (ptr) => {
                const str = readString(wasmExports.memory, ptr);
                const ts = Date.parse(str);
                return isNaN(ts) ? -1 : ts;
            },
            diffMs: (a, b) => a - b,

            // Regex
            regexTest: (patPtr, strPtr) => {
                try {
                    return new RegExp(readString(wasmExports.memory, patPtr))
                        .test(readString(wasmExports.memory, strPtr)) ? 1 : 0;
                } catch { return 0; }
            },
            regexMatch: (patPtr, strPtr) => {
                try {
                    const m = readString(wasmExports.memory, strPtr)
                        .match(new RegExp(readString(wasmExports.memory, patPtr)));
                    return m ? writeString(wasmExports, m[0]) : 0;
                } catch { return 0; }
            },
            regexReplace: (patPtr, strPtr, replPtr) => {
                try {
                    const result = readString(wasmExports.memory, strPtr)
                        .replace(new RegExp(readString(wasmExports.memory, patPtr), "g"),
                                 readString(wasmExports.memory, replPtr));
                    return writeString(wasmExports, result);
                } catch { return writeString(wasmExports, readString(wasmExports.memory, strPtr)); }
            },

            // Crypto (Workers crypto.subtle is async — use pure JS sync for sha256/md5)
            // Workers have crypto.randomUUID() and crypto.subtle, but subtle is async.
            // For sha256/md5/hmac, return empty string (matching CloudflareHostAdapter behavior
            // for operations that can't be done synchronously in Workers).
            sha256: (_ptr) => writeString(wasmExports, ""),
            md5: (_ptr) => writeString(wasmExports, ""),
            hmac: (_algo, _key, _data) => writeString(wasmExports, ""),

            // HTTP (Workers fetch is async — can't be called from sync host imports)
            httpGet: (urlPtr) => {
                // Return Err Result: tag=1 (Err), value=error string
                const errPtr = writeString(wasmExports, "fetch_not_available_sync");
                const resultPtr = allocateHeap(wasmExports, 16);
                const view = new DataView(wasmExports.memory.buffer);
                view.setInt32(resultPtr, 1, true);     // tag = Err
                view.setInt32(resultPtr + 8, errPtr, true); // error string
                return resultPtr;
            },
            httpPost: (urlPtr, bodyPtr) => {
                const errPtr = writeString(wasmExports, "fetch_not_available_sync");
                const resultPtr = allocateHeap(wasmExports, 16);
                const view = new DataView(wasmExports.memory.buffer);
                view.setInt32(resultPtr, 1, true);
                view.setInt32(resultPtr + 8, errPtr, true);
                return resultPtr;
            },
            httpPut: (urlPtr, bodyPtr) => {
                const errPtr = writeString(wasmExports, "fetch_not_available_sync");
                const resultPtr = allocateHeap(wasmExports, 16);
                const view = new DataView(wasmExports.memory.buffer);
                view.setInt32(resultPtr, 1, true);
                view.setInt32(resultPtr + 8, errPtr, true);
                return resultPtr;
            },
            httpDelete: (urlPtr) => {
                const errPtr = writeString(wasmExports, "fetch_not_available_sync");
                const resultPtr = allocateHeap(wasmExports, 16);
                const view = new DataView(wasmExports.memory.buffer);
                view.setInt32(resultPtr, 1, true);
                view.setInt32(resultPtr + 8, errPtr, true);
                return resultPtr;
            },

            // IO (Workers KV is async)
            readFile: (_pathPtr) => {
                const errPtr = writeString(wasmExports, "kv_not_available_sync");
                const resultPtr = allocateHeap(wasmExports, 16);
                const view = new DataView(wasmExports.memory.buffer);
                view.setInt32(resultPtr, 1, true);
                view.setInt32(resultPtr + 8, errPtr, true);
                return resultPtr;
            },
            writeFile: (_pathPtr, _contentPtr) => {
                const errPtr = writeString(wasmExports, "kv_not_available_sync");
                const resultPtr = allocateHeap(wasmExports, 16);
                const view = new DataView(wasmExports.memory.buffer);
                view.setInt32(resultPtr, 1, true);
                view.setInt32(resultPtr + 8, errPtr, true);
                return resultPtr;
            },
            env: (namePtr) => {
                const name = readString(wasmExports.memory, namePtr);
                const value = env[name] || "";
                return writeString(wasmExports, typeof value === "string" ? value : "");
            },
            args: () => {
                // No command-line args in Workers — return empty array
                const ptr = allocateHeap(wasmExports, 4);
                new DataView(wasmExports.memory.buffer).setInt32(ptr, 0, true);
                return ptr;
            },
            exit: (code) => { throw new Error("edict_exit:" + code); },
            panic: (ptr) => { throw new Error("edict_panic: " + readString(wasmExports.memory, ptr)); },
        };

        // ── WASM instantiation and execution ──────────────────────────

        try {
            const instance = await WebAssembly.instantiate(wasmModule, { host: hostFunctions });
            wasmExports = instance.exports;

            let exitCode = 0;
            try {
                const mainFn = wasmExports.main;
                if (typeof mainFn === "function") {
                    mainFn();
                }
            } catch (err) {
                const msg = err.message || String(err);
                const exitMatch = msg.match(/^edict_exit:(\\d+)$/);
                if (exitMatch) {
                    exitCode = parseInt(exitMatch[1], 10);
                } else {
                    outputParts.push("Runtime error: " + msg);
                    exitCode = 1;
                }
            }

            const output = outputParts.join("");
            const status = exitCode === 0 ? 200 : 500;
            return new Response(output, {
                status,
                headers: { "Content-Type": "text/plain; charset=utf-8" },
            });
        } catch (err) {
            return new Response("WASM instantiation error: " + (err.message || String(err)), {
                status: 500,
                headers: { "Content-Type": "text/plain; charset=utf-8" },
            });
        }
    }
};
`;
}

// =============================================================================
// Wrangler.toml generation
// =============================================================================

function generateWranglerToml(config: WorkerConfig): string {
    const compat = config.compatibilityDate ?? "2024-01-01";
    const lines: string[] = [
        `name = "${config.name}"`,
        `main = "worker.js"`,
        `compatibility_date = "${compat}"`,
    ];

    if (config.kvNamespaces && config.kvNamespaces.length > 0) {
        lines.push("");
        for (const kv of config.kvNamespaces) {
            lines.push(`[[kv_namespaces]]`);
            lines.push(`binding = "${kv.binding}"`);
            lines.push(`id = "${kv.id}"`);
            lines.push("");
        }
    }

    return lines.join("\n") + "\n";
}

// =============================================================================
// Public API
// =============================================================================

/**
 * Generate a deployable Cloudflare Worker bundle from compiled WASM.
 *
 * The bundle contains:
 * - `worker.js` — ES Module Worker entry point with all host imports inline
 * - `program.wasm` — the compiled WASM binary
 * - `wrangler.toml` — Wrangler v3 configuration
 *
 * Host functions in worker.js are derived from the ALL_BUILTINS registry at
 * generation time, matching CloudflareHostAdapter's behavior:
 * - Crypto: returns empty strings (async Workers crypto.subtle unusable in sync)
 * - HTTP: returns structured Result<String,String> Err values
 * - IO: returns structured errors (KV is async)
 * - env: reads from Workers environment bindings
 *
 * @param wasm - Compiled WASM binary (Uint8Array from codegen)
 * @param config - Worker configuration
 * @returns ScaffoldResult with the bundle or an error
 */
export function generateWorkerScaffold(
    wasm: Uint8Array,
    config: WorkerConfig,
): ScaffoldResult {
    // Input validation
    if (!wasm || wasm.length === 0) {
        return { ok: false, error: "wasm_empty" };
    }
    if (!config.name || config.name.trim().length === 0) {
        return { ok: false, error: "name_empty" };
    }

    const files: WorkerBundleFile[] = [
        { path: "worker.js", content: generateWorkerJs() },
        { path: "program.wasm", content: wasm },
        { path: "wrangler.toml", content: generateWranglerToml(config) },
    ];

    return { ok: true, bundle: { files } };
}

/**
 * Get the list of host builtin names included in the generated Worker script.
 * Useful for testing and verification.
 */
export function getHostBuiltinNames(): readonly string[] {
    return HOST_BUILTIN_NAMES;
}
